###
GET http://127.0.0.1:3000/api/books

###
GET http://127.0.0.1:3000/api/books?page=1&per=2

###
GET http://127.0.0.1:3000/api/books/1

###
GET http://127.0.0.1:3000/api/search/ruby

###
GET http://127.0.0.1:3000/api/books
Authorization: Alexandria-Token api_key=1:my_api_key

###
POST http://localhost:3000/api/users
Authorization: Alexandria-Token api_key=1:my_api_key
Content-Type: application/json

{
  "data": {
    "email":"john@gmail.com",
    "password": "password",
    "confirmation_redirect_url":"http://google.com"
  }
}

###
GET http://localhost:3000/api/books?sort=id&dir=asc
Accept-Encoding: gzip
Authorization: Alexandria-Token api_key=1:my_api_key

###
GET http://localhost:3000/api/books?sort=id&dir=asc
Authorization: Alexandria-Token api_key=1:my_api_key

###
GET http://localhost:3000/api/books?sort=id&dir=asc
Authorization: Alexandria-Token api_key=1:my_api_key
If-None-Match: W/"0361c209ef76da42d7002ed07816242c"

### check cache
GET http://localhost:3000/api/books?sort=id&dir=asc
Authorization: Alexandria-Token api_key=1:my_api_key